### ISSUE TITLE
Je n’arrive pas à détecter les Android TV 

### ISSUE THREAD

**Issue by technikosoldat** [louis49/homebridge-plugin-androidtv#1]
Bonjour, j’ai un Videoprojecteur et une freebox pop player qui tourne sous Android TV. Je n’arrive pas à comprendre comment les détecter pour que cela s’affiche sur Homekit. Comment trouver le port qu’il faut ? Après avoir installer le plugin comment les rajouter sur Homekit ? Merci pour l’aide

**Comment by louis49** [comment]
Une fois le plugin installé il faut se rendre sur le même host que homebridge avec le port 8182 (port par défaut que l’on peut configurer dans le plugin) 
De là, la liste des appareils android connectés au même réseau s’affichent : clic sur « Pair » - le code s’affiche sur la télé - le saisir dans le champ texte 
Une fois ça fait la télé doit s’afficher dans HomeKit quand on fait ajouter un accessoire

**Comment by technikosoldat** [comment]
Il faut donc que je mette la même adresse ip que mon Homebridge et je change le port en 8182 ?

**Comment by technikosoldat** [comment]
J’ai réussi. Super ! Par contre il n’affiche pas mon vidéo projecteur mais il affiche mes autres box Android. Mon Videoprojecteur est un Vava Chroma

**Comment by louis49** [comment]
Le projecteur est sous android ? En quelle version ?

**Comment by technikosoldat** [comment]
Il est sous Android mais il n’y a pas Android TV

**Comment by louis49** [comment]
Voilà le soucis alors ;-)

**Comment by technikosoldat** [comment]
Ha ok. Bon dommage. Et dernière question : J’éteins les deux box avec Homekit et quelques minutes après elle se remettent en allumé sur HK ? Une idée ?

**Comment by louis49** [comment]
Je vais corriger ça demain, je pense en avoir trouvé l’origine

**Comment by louis49** [comment]
Fixé dans la version [V2.0.11](https://github.com/louis49/homebridge-plugin-androidtv/releases/tag/V2.0.11)

**Comment by technikosoldat** [comment]
Merci beaucoup ! Super plugin
