### ISSUE TITLE
Play Store apps do not open directly

### ISSUE THREAD

**Issue by damienmauchamp** [louis49/homebridge-plugin-androidtv#10]
Hi, It looks like applications downloaded from the Play Store do not open directly (except for the gived examples), they redirects to the Play Store page instead.
Links I've tried this far (for [this app](https://play.google.com/store/apps/details?id=com.sfr.android.)) :

- https://play.google.com/store/apps/details?id=com.sfr.android.sfrsport&launch=true
- https://play.google.com/store/apps/details?id=com.sfr.android.sfrsport
- https://play.app.goo.gl/?link=https://play.google.com/store/apps/details?id=com.sfr.android.sfrsport&ddl=1&pcampaignid=web_ddl_1
- market://details?id=com.sfr.android.sfrsport

I've also tried the app official's urls like these but I got errors from them :

- https://www.rmcsport.tv/mon-espace-client/player.html#/tv
- https://www.rmcsport.tv/

(Android TV via Freebox Player Pop)

**Comment by damienmauchamp** [comment]
Small update, I've been trying to find solution, so I tried the way described on [the androidtv-remote repo](https://github.com/louis49/androidtv-remote):

> app_link : You can find them in some Android apps by seeking 'android:host' in Android-Manifest
You can use jadx to decompile the Android app and read Android-Manifest
Example : "https://www.netflix.com/title.*"

So I tried "sfrsport://alert" and "sfrsport://", none work.
Here's the content of the current version APK on the app I'm trying to include:

AndroidManifest.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="7213000" android:versionName="7.2.1" android:compileSdkVersion="30" android:compileSdkVersionCodename="11" package="com.sfr.android.sfrsport" platformBuildVersionCode="30" platformBuildVersionName="11">
    // ...
    <application android:theme="@style/Theme_Sport_Application" android:label="@string/app_name" android:icon="@mipmap/rmc_sport_icon" android:name="com.sfr.android.sfrsport.SportApplication" android:allowBackup="false" android:largeHeap="true" android:supportsRtl="true" android:usesCleartextTraffic="true" android:roundIcon="@mipmap/rmc_sport_icon_round" android:appComponentFactory="androidx.core.app.CoreComponentFactory">
        // ...
        <activity android:theme="@style/Theme_Sport_Splash" android:label="@string/app_name" android:name="com.sfr.android.sfrsport.SportMain" android:configChanges="keyboard|keyboardHidden|orientation|uiMode|screenSize">
            // ...
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <data android:scheme="@string/sport_scheme" android:host="@string/sport_host"/>
            </intent-filter>
            // ...
```


string.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    // ...
    <string name="sport_host">alert</string>
    // ...
    <string name="sport_scheme">sfrsport</string>
    // ...
```

**Comment by louis49** [comment]
Hi ! The app seems crappy : an "alert" host seems not conform
