### ISSUE TITLE
Applications configuration

### ISSUE THREAD

**Issue by EffeF** [louis49/homebridge-plugin-androidtv#16]
For `com.apple.atve.androidtv.appletv` my configuration is:
```JSON
{
    "name": "Apple TV",
    "link": "https://tv.apple.com/"
}
```
The app opens, but in a screen with a network error.

Also I would like to know the link for `com.google.android.tvlauncher`, so I can go back to home, and for `org.jellyfin.androidtv`, I searched for 'android:host' in Android-Manifest, but without finding a link for these apps.

**Comment by louis49** [comment]
Hello!
Can you post here these 3 differents Android-Manifest files ?

**Comment by EffeF** [comment]
Here are the files: [AndroidManifest.zip](https://github.com/louis49/homebridge-plugin-androidtv/files/8069406/AndroidManifest.zip)

**Comment by louis49** [comment]
For AppleTV app, could you try :
{"name": "Apple TV","link": "tv.apple.com"} and/or {"name": "Apple TV","link": "https://tv.apple.com"} ?
For TVLauncher, there is no android:host key. This library can push "home" button, that's what you need ? 
For Jellyfin, there is no android:host key. Maybe you can open a new issue at https://github.com/jellyfin ?

**Comment by EffeF** [comment]
> For AppleTV app, could you try :
{"name": "Apple TV","link": "tv.apple.com"} and/or {"name": "Apple TV","link": "[https://tv.apple.com"}](https://tv.apple.com%22%7D) ?

With `https://tv.apple.com` same behavior as mine `https://tv.apple.com/`

With `tv.apple.com`:
```console
[2/15/2022, 5:04:05 PM] [HomebridgeAndroidTV] SHIELD Sending linktv.apple.com
Create Remote {"remoteAppLinkLaunchRequest":{"appLink":"tv.apple.com"}}
Sending {"remoteAppLinkLaunchRequest":{"appLink":"tv.apple.com"}}
[2/15/2022, 5:04:05 PM] [HomebridgeAndroidTV] SHIELD set Active Identifier => setNewValue: 0
192.168.1.6 Remote Connection closed  false
Start Remote Connect
192.168.1.6 Error: connect ECONNREFUSED 192.168.1.6:6466
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.6',
  port: 6466
}
192.168.1.6 Remote Connection closed  true
ECONNREFUSED
Start Remote Connect
192.168.1.6 Remote secureConnect
192.168.1.6 Receive : {"remoteConfigure":{"code1":639,"deviceInfo":{"model":"SHIELD Android TV","vendor":"NVIDIA","unknown1":1,"unknown2":"11","packageName":"com.google.android.tv.remote.service","appVersion":"5.1.415324728"}}}
Create Remote {"remoteConfigure":{"code1":622,"deviceInfo":{"model":"Docker Container","vendor":"","unknown1":1,"unknown2":"1","packageName":"androitv-remote","appVersion":"1.0.0"}}}
Sending {"remoteConfigure":{"code1":622,"deviceInfo":{"model":"Docker Container","vendor":"","unknown1":1,"unknown2":"1","packageName":"androitv-remote","appVersion":"1.0.0"}}}
[2/15/2022, 5:04:07 PM] [HomebridgeAndroidTV] Discover :  {
  host: '192.168.1.6',
  name: 'SHIELD',
  paired: true,
  pairing: false,
  powered: true,
  online: true,
  started: true,
  volume_max: 0,
  volume_current: 0,
  volume_muted: false,
  app_package_current: '',
  type: 35
}
[2/15/2022, 5:04:07 PM] [HomebridgeAndroidTV] SHIELD Registering device
```

>  For TVLauncher, there is no android:host key. This library can push "home" button, that's what you need ?

I need to return to the Home.

**Comment by louis49** [comment]
I added a new functionality and publish it with [V2.1.0](https://github.com/louis49/homebridge-plugin-androidtv/releases/tag/V2.1.0) : you can now send 'Home' command
