### ISSUE TITLE
Can’t get code to connect

### ISSUE THREAD

**Issue by ghost** [louis49/homebridge-plugin-androidtv#19]
Hi, I was setting up this plugin with my UPT24K set-top box and when I try to connect to it via the home app it asks for a code. I tried with the Homebridge code but it didn’t work. What code do I have to enter?

**Comment by louis49** [comment]
The asked code when you add it to HomeKit is the Homebridge code. Try using QR code of Homebridge to pair it

**Comment by RobertBridda** [comment]
I already tried that, but it doesn’t work
