### ISSUE TITLE
App link

### ISSUE THREAD

**Issue by Willem-Si** [louis49/homebridge-plugin-androidtv#20]
Hi,

I have installed the plugin and almost everything is working as espected. Great Plugin!

I have 2 questions:

1: How can i easy find the app link for my installed apps? for example Discovery+
2; When i change the app using the tv remote the active app is not updated in the Homekit app, is this correct?

grtz,
Willem

**Comment by louis49** [comment]
Hi, 

For app link, it's explained here : https://github.com/louis49/androidtv-remote#command--sendapplinkapp_link

You need to download the apk, decompile it, seek 'android:host' in Android-Manifest : the address will be here

**Comment by Willem-Si** [comment]
Thx for the fast respose!

**Comment by juanvisbal** [comment]
I found [this link](https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921) with a compilation list of common apps.
