### ISSUE TITLE
Buttons only as input available 

### ISSUE THREAD

**Issue by novus84** [louis49/homebridge-plugin-androidtv#22]
Hello, 

I have added the following buttons from your example for testing. 

{
   "keys": [
      {"name": "Power", "key": "KEYCODE_POWER"},
      {"name": "VolUp", "key": "KEYCODE_VOLUME_UP"},
      {"name": "VolDown", "key": "KEYCODE_VOLUME_DOWN"},
      {"name": "Home", "key": "KEYCODE_HOME"},
      {"name": "Mute", "key": "KEYCODE_MUTE"}
   ]
}

But these are only shown as input, not as single buttons like e.g. Power.  Is this behavior normal? So the buttons are not really usable.

**Comment by louis49** [comment]
I do not understand what your are calling "input" : could you join a screenshot please ?

**Comment by novus84** [comment]
Hi, 

the "wheel" with the Inputs like HDMI1 etc. Or is it not possible to show e. g. Volume Up as a separate Button?  
![IMG_0304](https://user-images.githubusercontent.com/57588422/163673719-373c3f5c-74ec-4d75-9670-e525cc432032.png)

**Comment by louis49** [comment]
Yes : you can create a scene that activate this input and run it by voice - it's the only way actually
