### ISSUE TITLE
Connection lost after device is set to off

### ISSUE THREAD

**Issue by tamir61** [louis49/homebridge-plugin-androidtv#24]
Hey, I'm trying to use this plugin, I paired my Xiaomi MiBox4 (it connected via wifi)
it's working fine with turning off the device, but I can't set it back on after turning it off.

the homebridge terminal has lots of endless repeated logs:

`192.168.1.116 Error: connect EHOSTUNREACH 192.168.1.116:6466
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.116',
  port: 6466
}

**Comment by louis49** [comment]
Hi,
Try to disable deep sleep in AndroidTV settings
++

**Comment by tamir61** [comment]
So i read about Xiaomi mibox. Looks like the OS is overwriting this setting. So no way to make this plugin work with Xiaomi mibox. Thanks anyway

**Comment by louis49** [comment]
Sorry
