### ISSUE TITLE
How to reset the list of devices?

### ISSUE THREAD

**Issue by darkner258** [louis49/homebridge-plugin-androidtv#25]
Hello, how do i clear the list of devices in the admin? It doesnt show anywhere on the page.

**Comment by louis49** [comment]
Data are stored in a json file in your homebridge default folder : you can remove it to clean your list

**Comment by darkner258** [comment]
Thanks! How do I get to it if Im running the HB image on my RPi?

**Comment by louis49** [comment]
Indeed

I will try in next weeks to add a remove function if I have some time

**Comment by darkner258** [comment]
That would be awesome! Also one thing, when my TV turns off, it goes unresponsive (the network card is not powered). This cannot be changed, but when I turn on the TV manually with the remote, it does not show as on until I restart my HB.

**Comment by louis49** [comment]
You need to set your AndroidTV not deep sleeping : there is a option for that.
Normally a process check regularly if your device is on/online : except if IP change it should work. It's preferable to set a fixed IP.
