### ISSUE TITLE
Not completely understand how channels and apps works

### ISSUE THREAD

**Issue by Dukobpa3** [louis49/homebridge-plugin-androidtv#26]
Can I use it like `"send search request to TV to app"`?
Or `"Send Item to TV to be opened in the app"`?
Or `"Send search request to TV"`?

How can I operate with them?

I've added there Netflix, Youtube, Deezer. Would be great to be able to send something to tv from phone. EG open deezer link on it, or some Netflix series.

For now seems like I just can turn on TV with app opened and nothing more?

**Comment by louis49** [comment]
Hello @Dukobpa3 ,

Know first that HomeKit is extremely limited, it is not my will not to be able to perform the actions you mention.

Here's how it works and what's possible:

- You can create "Applications", which will allow you to have Prime, Netflix and your TV application (if you know the link to it - we can talk about it again if necessary on how to find the link that opens an application) .

- You can create "Channels", which will first make you go to the first application you have configured and then press the keys from 0 to 9 (like a remote control - this is also the remote control protocol that I use to do all this)

- You can create "Keys", to send this or that command to your AndroidTV (Mute, power, volume level or any other key on the remote control).

Once configured, these Application/Chains/Keys will appear as your device's "Input" within HomeKit. From there, you can create "Scenes", associated with this chosen device + input: you just have to ask Siri "Launch the Scene [scene name]" and it will obey you.

So, I hope I was clear enough in my explanation.

**Comment by Dukobpa3** [comment]
I will play with it. Thanks.

**Couple links for example:**
**Netflix Favorites:** https://www.netflix.com/browse/my-list
**Concrete item from Favorites:** https://www.netflix.com/browse/my-list?jbv=80204890

**Netflix Home:** https://www.netflix.com/browse
**Concrete item from Home:** https://www.netflix.com/browse?jbv=81140933
