### ISSUE TITLE
Functionality 

### ISSUE THREAD

**Issue by iteaky** [louis49/homebridge-plugin-androidtv#27]
Is it possible to make separate volume buttons near power button and some kind of joystick buttons? 
Now if you like to make volume up it like impossible with selecting that button from list with apps

**Comment by louis49** [comment]
No, it's not possible due to iOS and HomeKit limitations, but I'm waiting for iOS 16: I'll see what will be possible in this new context

**Comment by hunkyn** [comment]
Did not want to create another issue but my question is somewhat related. Is it possible to increase or decrease volume more than once? Right now when i click on VolumeDown it decreases by 1 and do not seem to have a way to reduce the volume further.
