### ISSUE TITLE
Play/Pause in Apple TV's controller

### ISSUE THREAD

**Issue by GalanAlex** [louis49/homebridge-plugin-androidtv#28]
Hi, can you fix action for button Play/Pause in Apple TV remote.
Now, action for Play/Pause is only play.
I think , if you cange in [platform.js](https://github.com/louis49/homebridge-plugin-androidtv/blob/main/src/homebridge/platform.js) 
keycode for play/pause from KEYCODE_MEDIA_PLAY to KEYCODE_MEDIA_PLAY_PAUSE they would work properly.

Thank you a lot and sorry if i'm wrong:)

**Comment by louis49** [comment]
Hi !

Good suggestion! Could you do a PR ?

**Comment by GalanAlex** [comment]
Of course. 
Thanks!

**Comment by louis49** [comment]
Thank you
