### ISSUE TITLE
the problem is in the name of the applications

### ISSUE THREAD

**Issue by Ivan-Hrabovyi** [louis49/homebridge-plugin-androidtv#31]
the problem is in the name of the applications when you want to set the path of the application like: com.youtube.tv. could you open the application using the name of the package?
Android tv homebridge

**Comment by louis49** [comment]
You need to use a link that appear in Android-Manifest of the application like explained here : https://github.com/louis49/homebridge-plugin-androidtv/issues/20

Please read closed Issues before submit a new one

**Comment by Ivan-Hrabovyi** [comment]
thank you, sorry to bother you
