### ISSUE TITLE
Where's the secret code?

### ISSUE THREAD

**Issue by randompea** [louis49/homebridge-plugin-androidtv#32]
I can't find a secret code, where would i find it?

**Comment by louis49** [comment]
It appears on TV after you start pairing

**Comment by randompea** [comment]
Okay. I use directv stream so let me try this.

**Comment by randompea** [comment]
I started pairing, nothing showed up. I set it as set box, all it shows is it started and i can hit the power button (doesnt work)

**Comment by randompea** [comment]
Nevermind, i needed to go to developer options and turn on like USB something..
