### ISSUE TITLE
Channel is not working if the TV is Off

### ISSUE THREAD

**Issue by andycylam** [louis49/homebridge-plugin-androidtv#33]
When the TV is off and I press any channel on Home app, the TV would switch on and go to home without pressing the enter button. I guess the reason is Homebridge emitting enter key code too early (or my TV is slow).

**Comment by louis49** [comment]
Hi,
Try to disable deep sleep in AndroidTV settings
++

**Comment by andycylam** [comment]
It is not in deep sleep. It can be turned on quite fast, but not fast enough to press the enter button. Probably the home app is slow.
