### ISSUE TITLE
How can I get this working with a Vodafone Sagemcom DCTI384 set top box?

### ISSUE THREAD

**Issue by rafacampoamor** [louis49/homebridge-plugin-androidtv#34]
Hi!

I installed your plugin (I understand it works with any AndroidTV device) but it seems not to find my Vodafone TV set top box (a Sagemcom DCTI384). 

I think it would be because the box is set to not be found but, if not, do you have a clue on how can I do that?

Thanks

**Comment by louis49** [comment]
I think could have an old version of Android that is not supported by this plugin - Google transformed the way to communicate with AndroidTV 2 years ago that's why I created this plugin : some other old plugins accept these old devices
