### ISSUE TITLE
Unable to add to HomeKit

### ISSUE THREAD

**Issue by tomeranaray** [louis49/homebridge-plugin-androidtv#35]
When trying to add my AndroidTV Setup box (Proximus Pickx), I was able to pair the setup box with HomeBridge. It’s also showing up in the HomeBridge UI under accessories where I can turn the device on and off. However, when adding to HomeKit, the process times out with an “unable to add accessory. Accessory is not reachable.”  There are no other error messages. 

Any suggestions what could go wrong?

**Comment by louis49** [comment]
What's the log says ?

**Comment by tomeranaray** [comment]
Nothing out of the ordinary. 
And today I tried again and it works just fine :) Sorry to have bothered you.
