### ISSUE TITLE
Can't access to the web GUI

### ISSUE THREAD

**Issue by MozkaGit** [louis49/homebridge-plugin-androidtv#36]
Hello, I'm running my homebridge server inside a docker container and I installed your plugin. The problem is that I can't access to the web page with http://_container_ip_:8182/

![image](https://user-images.githubusercontent.com/43102748/189570719-cf5645ef-fdcb-4d54-9f59-09bed74d6017.png)

I have no problem with the web interface of other docker containers so what am I doing wrong?

**Comment by louis49** [comment]
Do you access to HomeBridge url ?

**Comment by MozkaGit** [comment]
Yes with no problem

**Comment by louis49** [comment]
When starting server show running port in logs : using HomeBridge domain with this port isn't working ?

**Comment by MozkaGit** [comment]
When the startup logs are displayed I don't see ports related to your plugin (I only see ports for other plugins) 😕

**Comment by louis49** [comment]
Are you sure the plugin is installed and running ?

**Comment by MozkaGit** [comment]
I’m sure it’s installed but I can’t confirm you it’s running, can you explain me how can I check that please ?

![image](https://user-images.githubusercontent.com/43102748/189733072-9c277456-51c2-4bb9-9287-de89484fa6c3.png)
