### ISSUE TITLE
Installed on Raspberry Pi.   How to access local host?

### ISSUE THREAD

**Issue by holmstockd** [louis49/homebridge-plugin-androidtv#39]
The instructions are not that clear to me, sorry but where or what device do i run local host 8182?

**Comment by louis49** [comment]
On your HomeBridge server

**Comment by angelkr** [comment]
> On your HomeBridge server

sorry for bothering, could you talk us through the command exactly? can't seem to access it just by changing the url :/

**Comment by Treviko** [comment]
> > On your HomeBridge server
> 
> sorry for bothering, could you talk us through the command exactly? can't seem to access it just by changing the url :/

The plugin says: "Please, go to http://localhost:8182/ (change host to your) to see and add detected devices"

If you want to access the pairing page from remote you need to replace localhost with the ip address or dns of the home bridge instance which is running the plugin. 

http://INSERT_IP_OR_DNS:8182

And of course you must be able to reach the specified port remotely on your home bridge instance.

Hope this helps, I had a similar problem.
