### ISSUE TITLE
device not showing in homekit

### ISSUE THREAD

**Issue by chenks** [louis49/homebridge-plugin-androidtv#52]
device - nvidia shield tv

i've installed the plugin, configured it, paired the androidtv device.
the device works fine in homebridge. i can turn on and off the device from homebridge.
added the bridge to homekit, it added successfully, but no device shows up in home app.

restarted homebridge - still no luck

nothing in the homebridge logs to suggest any errors or issues.

so why is the device not showing up in homekit even after the bridge has been added to homekit?

**Comment by chenks** [comment]
is this a dead project ? @louis49 @lnking81 @GalanAlex

**Comment by mboeru** [comment]
I am trying out this plugin for the first time, and am seeing the same issue. homebridge shows the android tv, but that does not get exposed to homekit at all, and no errors are seen in logs.

**Comment by mboeru** [comment]
I've discovered that if you go to add accesory, after pairing it's bridge (I use child bridges), the Android TV will show up separately for some reason, and you can click it and input the main homebrige pairing code. Only then you will see it in Home app and be able to control it as advertised. Hope it helps.
FYI I use this for Chromecast with Google TV

**Comment by louis49** [comment]
Show me the logs and I will watch
