### ISSUE TITLE
Pairing new TV failing

### ISSUE THREAD

**Issue by amitmargalit** [louis49/homebridge-plugin-androidtv#9]
GUI works, trying to pair a Hair TV. clicking "pair", the code window immediately returns to the pair option.
HB log:
Start Pairing Connect
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1585:19)
    at TLSSocket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: '192.168.1.203',
  port: 6467,
  localAddress: undefined
}
192.168.1.203 Pairing Connection closed true
false

**Comment by amitmargalit** [comment]
config:
        {
            "port": 8182,
            "platform": "HomebridgeAndroidTV"
        }
        
if that matters, TV IP is static

**Comment by louis49** [comment]
Hi, 
What’s the AndroidTV version ?

**Comment by amitmargalit** [comment]
Latest. Just installed yesterday

**Comment by louis49** [comment]
Strange. It seems that the first connexion is not ok. Could you try by resetting androidtv-config.json and restart HomeBridge ?

**Comment by pparrilla** [comment]
Can i control the volume from homekit app? Because i paired and i can choose between netflix, prime or some programs, but about volume who can i do? Thanks for the plugin!

**Comment by skop1986** [comment]
@louis49 Hi, I have the same problem. After I deleted the TV and at home, I can't add it again. The home app does not detect the accessory

Thank you for your work!

**Comment by louis49** [comment]
Hi! 
I think it's a different problem.

You have multiple solutions to try : 

1. Change your device name : it will generate a new UUID, that will show a "new" device

2. Remove ".homebridge/persist" folder and restart

3.  In ".homebridge/config.json" change "bridge.username" value - but you will have to reconfigure all your devices

**Comment by skop1986** [comment]
Thanks! Deleting the ".homebridge/persist" folder helped me

**Comment by isklikas** [comment]
Hello!

I return to this issue because I'm facing the same problem. I have tried changing the device name, deleting the HomeBridge persist folder and deleting the androidtv-config.json and then reinstalling, only to face the same issue. The TV is a Toshiba Cosmos 9 (Android TV, of course, on the latest version). Any help is greatly appreciated!
